apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: circe-spring-boot
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: circe-spring-boot
      labels:
        app: circe-spring-boot
    spec:
      containers:
      - name: circe-spring-boot
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: gcr.io/<SOMETHING>/circe-spring:v1
