apiVersion: v1
kind: Service
metadata:
  name: circe-angular-service
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
  selector:
    app: circe-angular
  type: NodePort