apiVersion: v1
kind: Service
metadata:
  name: circe-spring-boot-service
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
      protocol: TCP
  selector:
    app: circe-spring-boot
  type: NodePort
